### ISSUE TITLE
IOError: Error reading file '/++theme++schools/rules.xml': failed to load external entity "/++theme++schools/rules.xml" 

### ISSUE THREAD

**Issue by shahbazfarooq** [quintagroup/quintagroup.theme.schools#1]
Please let me know how to fix this issue in plone. i am new in it. have worked in python. 

im just trying to retheme the plone site through diazo but constantly getting this issue. Please help

**Comment by waldru** [comment]
Please provide info on steps to reproduce the issue. What is the Plone and theme Versions?

**Comment by shahbazfarooq** [comment]
I am using Plone 4.3. the problem is when i tried to change the theme in it. it comes back with a list of errors. i was trying to get the schools theme but it didn't work. if you want me to attach a list of errors i will but the main error it was producing is mentioned above.

**Comment by waldru** [comment]
Schools theme works as expected. Issue you experience is not related to the theme itself but rather to the way you use trying to customize the theme.
